
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format-sql: true